### ISSUE TITLE
Top Gun - Combat Zones (USA) cannot start a new game (save issue)

### ISSUE THREAD

**Issue by benderscruffy** [fleroviux/NanoboyAdvance#105]
from another site about GBA saves

here’s only one game that contains three save codes, which is “Top Gun - Combat Zones”. It is a filthy liar, and if the game detects any of the storage types described by those save codes, it activates an anti-piracy routine and prevents you from picking any options in the main menu.

**Comment by fleroviux** [comment]
Hum, not sure whether this game is supposed to have backup memory at all.

**Comment by endrift** [comment]
This game does not have saves, but it probes the saves as an anti-piracy/anti-emulator trick.

**Comment by fleroviux** [comment]
Alright, thank you @endrift.
