### ISSUE TITLE
/usr/bin/ld: cannot find -lGLEW::glew

### ISSUE THREAD

**Issue by dashxdr** [fleroviux/NanoboyAdvance#107]
Ubuntu 18.04 LTS the build fails right at the final link stage. Here's some output with "make VERBOSE=1":

cd /ram/NanoboyAdvance/build/source/platform/sdl && /usr/bin/cmake -E cmake_link_script CMakeFiles/NanoboyAdvance.dir/link.txt --verbose=1
/usr/bin/c++   -Ofast  -rdynamic CMakeFiles/NanoboyAdvance.dir/main.cpp.o  -o NanoboyAdvance ../../libnba.a -Wl,-Bstatic -lSDL2main -Wl,-Bdynamic -lSDL2 -lpthread -lGL -lGLEW::glew ../../third_party/fmtlib/libfmt.a -lstdc++fs

I got it to link by cd'ing to that directory and changing -lGLEW::glew to just -lGLEW

**Comment by fleroviux** [comment]
Ugh, can't make this work the same way on all operating systems somehow, guess I'll have to special case it.

**Comment by fleroviux** [comment]
@dashxdr I have pushed a change that special-cases this (GLEW::glew on Apple devices and ${GLEW_LIBRARIES} everywhere else.) Can you confirm that this works for you?

**Comment by fleroviux** [comment]
@dashxdr Any update whether this fixed your.build issues?

**Comment by dashxdr** [comment]
Sorry for the delay, it's a random event when I go visit github these days.

The latest version DOES build successfully on my setup. Thanks!
