### ISSUE TITLE
Baldur's Gate: Dark Alliance (cannot save)

### ISSUE THREAD

**Issue by bryc** [fleroviux/NanoboyAdvance#108]
Saving does not seem to work in this game. It detects save type in console, but when I save and restart the program, it cannot find any saved data (seems initialized).

Using Windows 10.  I was dragging ROM directly over to the program, so maybe it is a path mismatch.

**Comment by fleroviux** [comment]
The emulator properly detects that this game uses EEPROM, but we can't know its size and the default value doesn't fit for this game. I will add a save type override to the game database to make it easier, to make it easier.

For the current version you can do the following:
1. delete the already created save file
2. on the console run `NanoboyAdvance.exe --save-type eeprom512 path_to_the_game` once
3. for subsequent runs you can just drag the ROM over the program, it should be able to get the proper save size from the already created file.

**Comment by fleroviux** [comment]
fixed in https://github.com/fleroviux/NanoboyAdvance/commit/03fe4145453fdde966ab1d786ce4721dd1014af2
