### ISSUE TITLE
GUI with ImGui

### ISSUE THREAD

**Issue by mrdeathjr28** [fleroviux/NanoBoyAdvance#113]
Hi

Maybe can add gui using:

Dear ImGui: Bloat-free Immediate Mode Graphical User interface for C++ with minimal dependencies

https://github.com/ocornut/imgui

Thanks

**Comment by fleroviux** [comment]
Dear ImGui already is on my mental TODO list

**Comment by fleroviux** [comment]
I decided to implement a frontend with Qt instead.
