### ISSUE TITLE
Sprites updated with HDMA differs from hardware

### ISSUE THREAD

**Issue by GValiente** [fleroviux/NanoboyAdvance#130]
Test rom:
[test.zip](https://github.com/mgba-emu/mgba/files/5148306/test.zip)

The first sprite lines in the image with length = 64 pixels are not shown on hardware.
Those lines are present in the last line of the sprite's image data.

![test](https://user-images.githubusercontent.com/13147012/91683188-30661c80-eb54-11ea-9f09-73c7219e90d3.png)

**Comment by fleroviux** [comment]
@GValiente can you provide source code to this test? this would make it a lot easier to debug for me.

**Comment by GValiente** [comment]
The test has been built on top on an engine that I'm planning to release at the end of this year, so if you don't mind to wait a few months I'll release the source code of this test with it.

If you can't wait, I can release part of the issues' related code. I think that the issue is related with that hdma on hardware in my rom seems to be two horizontal lines late, instead of only one.

**Comment by fleroviux** [comment]
I'm a bit confused how many lines are actually supposed to be missing on HW:
![image](https://user-images.githubusercontent.com/13669774/92286280-db852600-ef06-11ea-979e-b440fe7afa6d.png)
this is what I get on my GBA SP (sorry for the poor lighting condition). Can you confirm that all sprite lines with width=64 should be missing as seen on the image?

> If you can't wait, I can release part of the issues' related code. I think that the issue is related with that hdma on hardware in my rom seems to be two horizontal lines late, instead of only one.

I guess that might help but I had hoped to be able to make changes and test them on HW.

**Comment by GValiente** [comment]
Yep, those are the lines that are missing, the ones with width=64, which are rendered with the last line of the sprite's tiles: 

https://cdn.discordapp.com/attachments/312199400875360256/749564712437678160/example.png

**Comment by GValiente** [comment]
New [test ROM](https://github.com/mgba-emu/mgba/files/5524058/mgba_1871.zip).

The two biggest lines in the middle of the diamond are not visible on a real GBA:

![nba](https://user-images.githubusercontent.com/13147012/98814625-361a9100-2426-11eb-8767-ed74df30d57f.png)

The source code of the test ROM is available [here](https://github.com/GValiente/butano/tree/master/issues/mgba_1871).

**Comment by fleroviux** [comment]
Thanks!

**Comment by fleroviux** [comment]
<img width="592" alt="Bildschirmfoto 2021-02-07 um 01 08 05" src="https://user-images.githubusercontent.com/13669774/107132651-1db0fa00-68e1-11eb-9c51-50a2e9515ef4.png">
<img width="592" alt="Bildschirmfoto 2021-02-07 um 01 08 24" src="https://user-images.githubusercontent.com/13669774/107132654-21dd1780-68e1-11eb-982d-cdfaee314756.png">

This should perfectly match hardware now.
