### ISSUE TITLE
Vsync on high refresh monitors

### ISSUE THREAD

**Issue by jsmolka** [fleroviux/NanoBoyAdvance#134]
The emulator runs at the native monitor refresh rate which happens to be 144Hz in my case. Of course I could set `sync_to_audio = true` in the config but I don't think this should be the default behavior. I suspect this has something to do this has something to do with [SDL_GL_SetSwapInterval](https://wiki.libsdl.org/SDL_GL_SetSwapInterval) in [this](https://github.com/fleroviux/NanoboyAdvance/blob/6cdf99516e3d342dc0c7a96adf855b654452d4bc/source/platform/sdl/main.cpp#L294) line.

**Comment by fleroviux** [comment]
Yeah, this issue is not foreign to me. Good to have it tracked though. `sync_to_audio` was supposed to be the default solution, but it doesn't run great everywhere so far. So I guess I'll have to spend some time in general to rework the syncing options.
