### ISSUE TITLE
ROM OOB

### ISSUE THREAD

**Issue by mattrberry** [fleroviux/NanoBoyAdvance#144]
In November, jsmolka added [gba-suite/unsafe](https://github.com/jsmolka/gba-tests/blob/master/unsafe/unsafe.asm) which tests ROM OOB reads. According to the tests, the bytes following the ROM up to the next power of 2 should read 0. I'm making the assumption that this has been tested on hardware, but I haven't spoken to jsmokla. This "unsafe" test fails on test 3 on mGBA, test 2 on NanoBoyAdvance, and test 1 on my EZ-Flash Omega.

**Comment by mattrberry** [comment]
More discussion in the gbadev discord with endrift if you want to make your decision based off those comments

**Comment by fleroviux** [comment]
Closing because this doesn't concern commercial game paks, but only inaccurate flash cartridges.
