### ISSUE TITLE
Not opening on Mac OS 11.3 beta 6

### ISSUE THREAD

**Issue by Flemming7** [fleroviux/NanoBoyAdvance#149]
I have a problem... When I download the emulator and I want to open it I get a screen that says: App can't be opened cause the developer is no verified... after that is closes...

I found that this could be the problem: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution but I am not that technical...

macOS Version: 11.3 beta 6 (on the new Mac with Apple silicon)

**Comment by fleroviux** [comment]
Hi Flemming7,

we currently don't do any notoriation on the macOS binaries. It's something worth looking into for the next release maybe.
In the meantime you should be able to allow the app from the Security & Privacy settings:
https://www.macworld.co.uk/how-to/mac-app-unidentified-developer-3669596/

Let me know if this works for you.

**Comment by Flemming7** [comment]
Thanks I will try that!

**Comment by Flemming7** [comment]
Worked!!!
