### ISSUE TITLE
OBJ tiles should wrap around

### ISSUE THREAD

**Issue by emrsmsrli** [fleroviux/NanoBoyAdvance#173]
There's a broken sprite in Advance Wars 2 Versus-Rules screen. This sprite starts from 0x3FA in obj tile memory and ends in out-of-bounds. I'm not sure what the correct behavior should be, but I believe that the tile numbers should wrap around when they go beyond 1024.

![image](https://user-images.githubusercontent.com/16121887/131252230-281f974f-08b1-431e-8dde-e1d5582afcb1.png)

Here's a snapshot of the obj tile memory while in that screen:

![image](https://user-images.githubusercontent.com/16121887/131252366-3df17684-544f-44bb-872f-8b9909c6a837.png)

**Comment by fleroviux** [comment]
Well, it is fixed on the `libnba` branch now. Still needs to be merged though.
