### ISSUE TITLE
Perform prefetch of next instruction instead of current.

### ISSUE THREAD

**Issue by fleroviux** [fleroviux/NanoboyAdvance#37]
To get accurate timings we want to perform the prefetch of the next instruction
in the current one. The reason for that is that we need to know whether the prefetch will be sequential (current instruction accessed no other data) or non-sequential (current instruction accessed unrelated data, ldr/str e.g.).

To do this we need to do the following:
1. Increase size of `pipe` to 3 elements.
2. When refilling the pipeline fetch 3 instructions instead of 2 (though keep current r15 increment).
3. Prefetch after incrementing r15, adjust prefetch element to 3-element size of pipeline.
4. "Remove" prefetches that just "happen" because they can't be stopped anymore.

**Comment by flerovii** [comment]
Another way to solve this problem could be to pipeline the type of the next access.
This is also likely what the actual HW does?

**Comment by fleroviux** [comment]
Started work on this.
Missing stuff:
- Thumb LDM/STM, PUSH/POP
- Any ARM instructions
