### ISSUE TITLE
Some sort of softlock

### ISSUE THREAD

**Issue by daniel-poole** [fleroviux/NanoboyAdvance#43]
Issue: when running Pokemon Emerald, the game gets in some sort of loop. The screen will flash green twice, and then turn black. Pressing Z will send you to the clock battery screen, and then show you New Game, which does not work.

Steps to Reproduce: 
1. Run PKE ROM
2. Go past Game Freak logo
3. Wait for the two green flashes, and press Z.

I assume you know about this, but it wasn't documented so I felt it necessary.

**Comment by daniel-poole** [comment]
That's weird, if you press X at the right time it seems to work.

**Comment by daniel-poole** [comment]
never mind I'm an idiot

**Comment by fleroviux** [comment]
No worries, it's just a video mode that's not implemented yet.
