### ISSUE TITLE
Bitmap backgrounds should support rotation / scaling

### ISSUE THREAD

**Issue by jsmolka** [fleroviux/NanoboyAdvance#73]
Bitmap backgrounds should support rotation / scaling like affine tiled backgrounds ([GBATEK](https://problemkaputt.de/gbatek.htm#lcdiodisplaycontrol)). [This game](https://www.gbadev.org/demos.php?showinfo=583) uses bitmap mode 3 (160x128) and then scales to the full display by setting parameters PA and PD to 0x80.

**Comment by fleroviux** [comment]
That's a valid point. I know that the bitmap modes support affine transforms, but
wasn't aware of anything that actually uses it. So it's good to know that this is required for some games.

Thanks,
fleroviux
