### ISSUE TITLE
CMake issues on linux

### ISSUE THREAD

**Issue by Mte90** [fleroviux/NanoboyAdvance#81]
I got this issues https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951087 and https://github.com/JACoders/OpenJK/pull/1033
That not let to find SDL2.
TO fix is enough toremove the cmake folder and he cmakelists inside qt/sql remove the `include` parameter and fix the next line with the variable `SDL2_INCLUDE_DIRS`.

Later I am getting his error of QT on compiling it:

```
/NanoboyAdvance/source/./platform/qt/mainwindow.hpp:42:22: error: ‘QActionGroup’ does not name a type
   42 |     auto group = new QActionGroup{this};
NanoboyAdvance/source/./platform/qt/mainwindow.hpp:50:33: error: incomplete type ‘QAction’ used in nested name specifier
   50 |       connect(action, &QAction::triggered, [=]() {
```

**Comment by Mte90** [comment]
The QT errors was easy to fix with adding on mainwindow.hhp `#include <QActionGroup>`

**Comment by fleroviux** [comment]
I merged the pull request but I'll have to look into the SDL2 part. 
It will probably require some extra work to get it to compile on Windows and potentially Mac OS X,
since CMake needs some way to locate SDL2 after all.

**Comment by fleroviux** [comment]
According to the Debian bugtracker this issue was resolved on their end.
Removing FindSDL2.cmake isn't compatible with other platforms like Windows, so I'll leave it at this.
