### ISSUE TITLE
cant use it

### ISSUE THREAD

**Issue by heckez-sys** [fleroviux/NanoboyAdvance#85]
i dont have cmake and stuff so can you make a release?

**Comment by fleroviux** [comment]
Currently some things are not polished enough that I would want to put out binaries,
so no. A binary release will follow eventually, but not now.

**Comment by fleroviux** [comment]
@heckez-sys If you use Windows binaries are now available.
https://github.com/fleroviux/NanoboyAdvance/releases/tag/v1.1
