### ISSUE TITLE
Building issues on macOS 

### ISSUE THREAD

**Issue by azoreseuropa** [fleroviux/NanoboyAdvance#88]
I build many emulators on macOS and it is not new to me. I have a problem:

git clone --recurse-submodules https://github.com/fleroviux/NanoboyAdvance.git

cd NanoboyAdvance
mkdir build
cd build
cmake ..

I got this error:

[ 97%] Building CXX object source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/main.cpp.o
/Users/azoreseuropa/NanoboyAdvance/source/platform/sdl/main.cpp:27:10: fatal error: 
      'GL/glew.h' file not found
#include "GL/glew.h"
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/main.cpp.o] Error 1
make[1]: *** [source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/all] Error 2
make: *** [all] Error 2

**Help?** I already brew install glew if you must know.

**Comment by fleroviux** [comment]
According to a friend who compiled the emulator on macOS recently,
this can be worked around by adding GLEW to the C++ include path manually:
```bash
export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/glew/include"
```
Let me know whether this works or not. Unfortunately I can't test on macOS myself.

**Comment by fleroviux** [comment]
Could you please also run `cmake -LAH` from the build directory and send the output?

**Comment by azoreseuropa** [comment]
[ 97%] Building CXX object source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/main.cpp.o
/Users/azoreseuropa/NanoboyAdvance/source/platform/sdl/main.cpp:171:23: warning: 
      enumeration value 'Ok' not handled in switch [-Wswitch]
  switch (g_emulator->LoadGame(rom_path)) {
                      ^
/Users/username/NanoboyAdvance/source/platform/sdl/main.cpp:171:23: note: 
      add missing switch cases
  switch (g_emulator->LoadGame(rom_path)) {
                      ^
1 warning generated.
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework', needed by `source/platform/sdl/NanoboyAdvance'.  Stop.
make[1]: *** [source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/all] Error 2
make: *** [all] Error 2

**Comment by fleroviux** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework`
Can you check whether that path exists on your system? If not then maybe you don't have the maxOS 10.15 SDK installed according to the aforementioned friend.

I also pushed a small commit a few minutes ago to mitigate a GLEW linking problem on macOS that should come up later otherwise, so please make sure to update your local copy.

**Comment by fleroviux** [comment]
(fwiw if you're just looking to try the emulator, my friend was nice enough to just provide macOS binaries to me, which should hopefully work https://github.com/fleroviux/NanoboyAdvance/releases/tag/v1.1)

**Comment by azoreseuropa** [comment]
Thank you for this but can you maybe ask your friend to give us an instruction on how to build it for macOS ? I would love to. 

And what update my local copy are you talking about ? Everything are the latest update as always unless I am missing something ?

**Comment by fleroviux** [comment]
> And what update my local copy are you talking about ? Everything are the latest update as always  unless I am missing something ?

I made a change yesterday, after you created this issue, that should already fix one the issues that come up when compiling on macOS. I was just asking you to get the latest source with this change to make sure the issue doesn't come up later :)
https://github.com/fleroviux/NanoboyAdvance/commit/29d8d35db3e7d82a2bce10d8b2e7646115a1a58a

> Thank you for this but can you maybe ask your friend to give us an instruction on how to build it for macOS ? I would love to.

They say they installed SDL2 and GLEW via brew and also have the macOS 10.15 SDK installed.
Besides having to add GLEW to the include path manually, it should then build as usual.


> 
> 
> `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework`
> Can you check whether that path exists on your system? If not then maybe you don't have the macOS 10.15 SDK installed according to the aforementioned friend.

Do you have the macOS 10.15 SDK installed? And does this path exist on your system at all?

**Comment by azoreseuropa** [comment]
Thank you. :)

Same error  since 97 percent incomplete but I didn't installed macOS 10.15 SDK installed. Is that really necessarily for just this emulator. My emulators that I built never asked for it. It is the first time I have seen it.

**Comment by fleroviux** [comment]
I don't know what the intended way to get OpenGL development libraries on macOS is, but I am certain that the way I setup CMake to search for OpenGL is as intended. I only declare that I require it and CMake handles actually locating it. I'm not sure what I am supposed to do differently in this case. If CMake on macOS tries to locate it via the macOS 10.15 SDK, then installing that seems like the proper solution to me.

**Comment by azoreseuropa** [comment]
> I don't know what the intended way to get OpenGL development libraries on macOS is, but I am certain that the way I setup CMake to search for OpenGL is as intended. I only declare that I require it and CMake handles actually locating it. I'm not sure what I am supposed to do differently in this case. If CMake on macOS tries to locate it via the macOS 10.15 SDK, then installing that seems like the proper solution to me.


Thank you. That's alright. As long as your friend can share it with us. That would be great. :) Keep up the good work! And sorry to bother you.

**Comment by fleroviux** [comment]
https://github.com/fleroviux/NanoboyAdvance/commit/c02e229c40ab2ab3338367097a68e216cac9a1bc
I have added additional information for users who want to build the code on macOS.

**Comment by azoreseuropa** [comment]
Almost! Here:

[ 97%] Building CXX object source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/main.cpp.o
/Users/username/NanoboyAdvance/source/platform/sdl/main.cpp:171:23: warning: 
      enumeration value 'Ok' not handled in switch [-Wswitch]
  switch (g_emulator->LoadGame(rom_path)) {
                      ^
/Users/username/NanoboyAdvance/source/platform/sdl/main.cpp:171:23: note: 
      add missing switch cases
  switch (g_emulator->LoadGame(rom_path)) {
                      ^
1 warning generated.
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework', needed by `source/platform/sdl/NanoboyAdvance'.  Stop.
make[1]: *** [source/platform/sdl/CMakeFiles/NanoboyAdvance.dir/all] Error 2
make: *** [all] Error 2

**Comment by fleroviux** [comment]
@azoreseuropa Yes I only added information on what needs to be done according to my knowledge.
FWIW we now have automated builds that include macOS:
https://github.com/fleroviux/NanoboyAdvance/actions

**Comment by azoreseuropa** [comment]
> @azoreseuropa Yes I only added information on what needs to be done according to my knowledge.
> FWIW we now have automated builds that include macOS:
> https://github.com/fleroviux/NanoboyAdvance/actions

I understand. And I thank you for include macOS. Please continue include it for regularly builds. Much appreciated and keep up the good work!
