### ISSUE TITLE
Acrobat Kid (Japan) doesnt boot

### ISSUE THREAD

**Issue by benderscruffy** [fleroviux/NanoboyAdvance#92]
nothing but a white screen

**Comment by fleroviux** [comment]
Can confirm.

**Comment by fleroviux** [comment]
All this game needed was a save type override, I added an entry to the game database.
A quick search on http://offlinelistgba.free.fr/index.php only returned a japan release,
are you aware of any other releases that should be added to the database?

**Comment by benderscruffy** [comment]
i will check the database
good job with the fixes so far
